"""Author the portable static portfolio. Run with Python 3; no dependencies."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'docs'
OUT.mkdir(parents=True, exist_ok=True)
LINKEDIN = 'https://www.linkedin.com/in/ln-abhisheksharma/'
EMAIL = 'mailto:abhisheksharma0217@gmail.com'

SECTION_NAV = (
    ('overview', 'Overview'),
    ('work', 'Work'),
    ('experience', 'Experience'),
    ('publications', 'Publications'),
    ('contact', 'Contact'),
)

def header(is_home):
    items = []
    for key, label in SECTION_NAV:
        href = f'#{key}' if is_home or key == 'contact' else f'./index.html#{key}'
        current = ' aria-current="location"' if key == ('overview' if is_home else 'work') else ''
        items.append(f'<li data-nav-section="{key}"><a class="rail-link" data-section-key="{key}" href="{href}"{current}><span class="rail-marker" aria-hidden="true"></span><span class="rail-label">{label}</span><span class="rail-progress" aria-hidden="true"></span></a></li>')
    rail = '<aside class="section-rail"><nav aria-label="Portfolio sections"><p class="rail-caption">Contents</p><ol>' + ''.join(items) + '</ol></nav></aside>'
    return '''<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner">
<a class="brand" href="./index.html" aria-label="Abhishek Sharma, home"><span class="brand-mark" aria-hidden="true">AS</span><span>Abhishek Sharma</span></a>
</div></header>''' + rail

def footer():
    return f'''<section class="contact-section" id="contact" aria-labelledby="contact-title"><div class="wrap contact-layout"><div><p class="eyebrow">Contact</p><h2 id="contact-title">Let's talk engineering.</h2><p>Embedded sensing, signal processing, and intelligent devices.<br>Based in Freiburg, Germany.</p></div><div class="contact-links"><a href="{EMAIL}">Email Abhishek <span aria-hidden="true">↗</span></a><a href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn <span aria-hidden="true">↗</span></a></div></div></section>
<footer class="site-footer"><div class="wrap footer-inner"><span>© 2026 Abhishek Sharma</span><span>Embedded systems · Sensing · Signal processing</span><a href="#top">Back to top ↑</a></div></footer>'''

def page(filename, title, description, body):
    is_home = filename == 'index.html'
    page_class = 'portfolio-home' if is_home else 'portfolio-case'
    html = f'''<!doctype html>
<html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="description" content="{description}"><title>{title}</title><link rel="icon" href="./favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles.css"><link rel="stylesheet" href="./navigation.css"><script src="./navigation.js" defer></script></head><body class="{page_class}">{header(is_home)}{body}{footer()}</body></html>'''
    (OUT / filename).write_text(html + '\n', encoding='utf-8')

def diagram():
    return '''<svg class="architecture" viewBox="0 0 450 325" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="architecture-title architecture-description">
<title id="architecture-title">Pressure sensing architecture</title><desc id="architecture-description">ABP2 gauge pressure over SPI, MPR absolute pressure and SHT45 temperature over I2C connect to an ESP32-S2 acquisition node. Recorded data are evaluated in Python.</desc>
<defs><marker id="head" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="none" stroke="#7299ff" stroke-width="1.4"/></marker></defs>
<g fill="none" stroke="#4f6e9b" stroke-width="1.2"><path d="M176 44H207V116H238"/><path d="M176 126H238" marker-end="url(#head)"/><path d="M176 208H207V136H238"/><path d="M330 169V238" marker-end="url(#head)"/></g>
<g font-family="Arial,sans-serif"><g fill="#182a45" stroke="#415a80"><rect x="0.8" y="12" width="176" height="65"/><rect x="0.8" y="94" width="176" height="65"/><rect x="0.8" y="176" width="176" height="65"/></g>
<g fill="#eaf0ff" font-size="16"><text x="15" y="38">Gauge pressure</text><text x="15" y="120">Absolute pressure</text><text x="15" y="202">Temperature</text></g>
<g fill="#a9bddb" font-size="13"><text x="15" y="60">ABP2 / SPI</text><text x="15" y="142">MPR / I²C</text><text x="15" y="224">SHT45 / I²C</text></g>
<rect x="240" y="87" width="177" height="82" fill="#2448a1" stroke="#7195ef"/><text x="258" y="119" fill="white" font-size="20">ESP32-S2</text><text x="258" y="146" fill="#d2dfff" font-size="13">Acquisition + firmware</text>
<text x="344" y="209" fill="#a9bddb" font-size="12">Data stream</text><rect x="240" y="240" width="177" height="63" fill="#182a45" stroke="#415a80"/><text x="258" y="266" fill="#eaf0ff" font-size="16">Python analysis</text><text x="258" y="289" fill="#a9bddb" font-size="13">Time series + models</text></g></svg>
<div class="mobile-architecture"><dl><div><dt>Gauge pressure</dt><dd>ABP2 / SPI</dd></div><div><dt>Absolute pressure</dt><dd>MPR / I²C</dd></div><div><dt>Temperature</dt><dd>SHT45 / I²C</dd></div></dl><div class="mobile-node"><strong>ESP32-S2</strong><span>Acquisition + firmware</span></div><div class="mobile-analysis"><strong>Python analysis</strong><span>Recorded time series + models</span></div></div>'''

home = f'''<main id="main"><div class="wrap"><section class="hero" id="overview" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">Embedded systems engineer · Freiburg</p><h1 id="hero-title">Embedded systems,<br>from sensing<br>to <span>intelligence.</span></h1><p>I build sensing and measurement systems that connect hardware, firmware, and signal processing. My work turns physical measurements into interpretable data, with a growing focus on on-device intelligence.</p><div class="hero-actions"><a class="button" href="#work">Explore my work <span class="arrow" aria-hidden="true">↓</span></a><a class="text-link" href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn <span class="arrow" aria-hidden="true">↗</span></a></div></div>
<div class="diagram-panel"><div class="diagram-heading"><span>A system I've built</span><span>PRESSURE SENSING</span></div>{diagram()}<div class="diagram-footer"><span>Sensor interfaces → acquisition → analysis</span><span>01 / 02</span></div></div></section>
<div class="hero-meta"><div><span class="eyebrow">Based in</span><p>Freiburg, Germany</p></div><div><span class="eyebrow">Starting October 2026</span><p>Embedded AI &amp; Ubiquitous Computing</p></div><div><span class="eyebrow">Foundation</span><p>M.Sc. Embedded Systems Engineering</p></div></div>
<section class="section" id="work" aria-labelledby="work-title"><div class="section-head"><div><p class="eyebrow">Selected work</p><h2 id="work-title">Engineering in practice.</h2></div><p>Two case studies in building, interpreting, and maintaining technical systems.</p></div><div class="project-grid">
<article class="project-card featured"><div class="project-topline"><span class="project-index">01 / Embedded systems</span><span>Doctoral research</span></div><h3>Making slow physical<br>processes measurable.</h3><p>Optical and pressure-sensing platforms, embedded acquisition, and model-based analysis for long-duration experiments.</p><div class="tags"><span class="tag">ESP32</span><span class="tag">SPI / I²C</span><span class="tag">Signal processing</span><span class="tag">Python</span></div><a class="text-link" href="./sensing.html">Read the engineering case study <span class="arrow" aria-hidden="true">↗</span></a></article>
<article class="project-card"><div class="project-topline"><span class="project-index">02 / Operational software</span><span>University Medical Center</span></div><h3>Keeping clinical reporting<br>maintainable.</h3><p>e-Testing: a hospital intranet platform for psychological test results, reporting workflows, and repeatable instrument integration.</p><div class="tags"><span class="tag">Flask</span><span class="tag">MariaDB</span><span class="tag">Automation</span><span class="tag">Technical handover</span></div><a class="text-link" href="./etesting.html">Read the engineering case study <span class="arrow" aria-hidden="true">↗</span></a></article>
</div></section></div>
<section class="section experience-section" id="experience" aria-labelledby="experience-title"><div class="wrap experience-layout"><div class="section-intro"><p class="eyebrow">Experience &amp; direction</p><h2 id="experience-title">Hardware depth.<br>System ownership.</h2><p>My background connects embedded measurement, communications engineering, and software used in research and clinical workflows.</p><p>In October 2026, I join Prof. Oliver Amft's Chair of Embedded AI and Ubiquitous Computing.</p></div><div>
<article class="timeline-row"><div class="timeline-date">Oct 2026</div><div><h3>Embedded AI &amp; Ubiquitous Computing</h3><p class="timeline-org">Research position · Prof. Oliver Amft</p><span class="status">Upcoming</span><p class="timeline-description">A new focus on embedded intelligence, sensing systems, and research project delivery.</p></div></article>
<article class="timeline-row"><div class="timeline-date">2023–2026</div><div><h3>Doctoral research</h3><p class="timeline-org">University of Freiburg · IMTEK / livMatS</p><p class="timeline-description">Optical and pressure-based instrumentation, embedded acquisition, signal processing, and physics-informed models. Research work completed; thesis submission and defense pending.</p></div></article>
<article class="timeline-row"><div class="timeline-date">2022–2026</div><div><h3>Research software development</h3><p class="timeline-org">University Medical Center Freiburg</p><p class="timeline-description">Development and maintenance of e-Testing, including reporting automation, instrument integration, and technical handover.</p></div></article>
<article class="timeline-row"><div class="timeline-date">2020–2022</div><div><h3>Communications modelling</h3><p class="timeline-org">Deutsche Bahn AG · Working student</p><p class="timeline-description">MATLAB propagation and channel models for FRMCS/5G scenarios, supported by field-trial data and multi-antenna analysis.</p></div></article>
<details class="earlier-work"><summary>Earlier industry experience</summary><p><strong>Mercedes-Benz AG · Research intern · 2020</strong><br>LTE module integration with carPC platforms and automation of in-vehicle measurement logging.</p><p><strong>HFCL Group · Assistant Manager · 2017–2019</strong><br>Technical planning and deployment of telecom and wireless systems, with contributions to RF hardware development.</p></details>
</div></div></section>
<section class="section wrap" id="publications" aria-labelledby="publications-title"><div class="section-head"><div><p class="eyebrow">Research evidence</p><h2 id="publications-title">Selected publications.</h2></div><p>Peer-reviewed work supporting the sensing, measurement, and modelling case study.</p></div><div class="publications">
<article class="publication-row"><span class="publication-year">2026</span><div><h3><a href="https://doi.org/10.1021/acsomega.6c06043" target="_blank" rel="noopener noreferrer">Kinetic Modeling and Quantification of Pressure-Derived Oxygen Accumulation from Anthracene Endoperoxides under Confined Conditions</a></h3><p>ACS Omega · Gauge and absolute pressure sensing with kinetic quantification.</p></div><a class="arrow" href="https://doi.org/10.1021/acsomega.6c06043" target="_blank" rel="noopener noreferrer" aria-label="Open pressure quantification paper">↗</a></article>
<article class="publication-row"><span class="publication-year">2026</span><div><h3><a href="https://doi.org/10.1016/j.snb.2025.138667" target="_blank" rel="noopener noreferrer">Oxygen sensor system: Real-time absorbance-based monitoring system for tracking oxygen release from tunable anthracene-endoperoxide molecules</a></h3><p>Sensors and Actuators B: Chemical · Optical instrumentation and experimental validation.</p></div><a class="arrow" href="https://doi.org/10.1016/j.snb.2025.138667" target="_blank" rel="noopener noreferrer" aria-label="Open optical sensing paper">↗</a></article>
<article class="publication-row"><span class="publication-year">2025</span><div><h3><a href="https://doi.org/10.1021/acsomega.5c07255" target="_blank" rel="noopener noreferrer">Pressure Sensing and Kinetic Modeling of Oxygen-Releasing Endoperoxides for Chemically Driven Micro-Actuation</a></h3><p>ACS Omega · Pressure acquisition, signal processing, and kinetic modelling.</p></div><a class="arrow" href="https://doi.org/10.1021/acsomega.5c07255" target="_blank" rel="noopener noreferrer" aria-label="Open pressure sensing paper">↗</a></article>
</div><p class="pub-context">First-author publications from interdisciplinary research at the University of Freiburg.</p></section></main>'''
page('index.html','Abhishek Sharma | Embedded Systems & Sensing','Embedded systems engineer in Freiburg. Sensing, firmware, signal processing, model-based analysis, and a growing focus on on-device intelligence.',home)

def case_top(category,title,lead,rows):
    summary=''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in rows)
    return f'''<main id="main"><div class="wrap"><section class="case-hero"><a class="back-link" href="./index.html#work"><span aria-hidden="true">←</span> All selected work</a><div class="case-heading"><div><p class="eyebrow">{category}</p><h1>{title}</h1><p class="case-lead">{lead}</p></div><dl class="case-summary">{summary}</dl></div></section>'''

sensing=case_top('01 / Embedded sensing & measurement','Making slow physical<br>processes measurable.','From optical and pressure sensors to recorded signals, interpretable models, and explicit measurement limits.',[('Context','Doctoral research · University of Freiburg'),('My contribution','Instrumentation, acquisition, signal processing, and model-based analysis'),('Platforms','ESP32-S2 · Optical sensing · Python'),('Evidence','Three first-author journal articles')])
sensing+=f'''<div class="case-layout"><nav class="case-nav" aria-label="Case study sections"><a href="#problem">The problem</a><a href="#architecture">System architecture</a><a href="#decisions">Engineering decisions</a><a href="#evidence">Measured evidence</a><a href="#on-device">On-device direction</a><a href="#sources">Publications</a></nav><div class="case-content">
<section class="case-section" id="problem"><p class="eyebrow">The problem</p><h2>A sensor reading needs a measurement model.</h2><p>Slow gas release creates a demanding instrumentation problem. The signal evolves over hours or days, and temperature changes, baseline drift, sensor referencing, and the chamber itself all affect the observed response.</p><p>My doctoral work addressed this through complementary optical and pressure-based platforms. The application was oxygen release from anthracene endoperoxides (ANT-EPO) in confined systems. The engineering task was to make that process observable, record it continuously, and establish what the measurements could support.</p><div class="technical-note"><strong>My scope</strong>I developed sensing and acquisition platforms, integrated experimental hardware, and built the signal-processing and quantitative analysis workflows. Compound development and synthesis formed part of the wider interdisciplinary collaboration.</div></section>
<section class="case-section" id="architecture"><p class="eyebrow">System architecture</p><h2>Connected hardware and analysis.</h2><p>The pressure platform combines a sensitive gauge channel with an absolute-pressure channel and local temperature measurement. An ESP32-based controller supports continuous acquisition and display; host-side software records and analyses the resulting time series.</p><div class="case-diagram">{diagram()}</div><p class="no-script-note">Simplified architecture of the ESP32-S2 pressure-acquisition platform.</p>
<figure class="figure"><div class="hardware-panel"><img src="./assets/pressure-platform-source.png" width="1254" height="710" loading="lazy" alt="Experimental pressure-sensing prototype with two Schlenk tubes, gauge and absolute sensors, local temperature sensing, an OLED display and a microcontroller."></div><figcaption>Pressure-sensing prototype. Detail of Figure 1(b), Sharma et al., <a href="https://doi.org/10.1021/acsomega.6c06043" target="_blank" rel="noopener noreferrer">ACS Omega, 2026</a>. The photograph shows the parallel gauge and absolute measurement arrangements. Displayed crop; licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a>.</figcaption></figure>
<table class="facts-table"><caption class="eyebrow" style="text-align:left;margin-bottom:8px">The pressure platform</caption><tbody><tr><th scope="row">Gauge pressure</th><td>Honeywell ABP2, 0–16 kPa range, SPI interface.</td></tr><tr><th scope="row">Absolute pressure</th><td>Honeywell MPR family, I²C interface.</td></tr><tr><th scope="row">Environment</th><td>Sensirion SHT45 temperature and humidity sensing, I²C.</td></tr><tr><th scope="row">Acquisition</th><td>Adafruit QT Py ESP32 platform, local OLED display, continuous host logging.</td></tr><tr><th scope="row">Interpretation</th><td>Time-series processing, baseline assessment, parameter estimation, and pressure-to-gas modelling.</td></tr></tbody></table>
<h3>A complementary optical platform</h3><p>Two optical paths at 265 nm and 400 nm use reference and sample photodetectors, amplification, and a custom housing. Calibration and comparison with benchtop UV–vis measurements connect detector voltages to absorbance and molecular conversion.</p></section>
<section class="case-section" id="decisions"><p class="eyebrow">Engineering decisions</p><h2>Design around the uncertainty.</h2><h3>Use complementary pressure references</h3><p>Gauge and absolute sensors provide different reference points. Parallel measurements of identically prepared samples help assess consistency and environmental effects. The channels measure separate sample tubes, so agreement is interpreted within the experimental configuration.</p><h3>Account for temperature and geometry</h3><p>Converting pressure into gas amount requires a defined headspace and a temperature model. Gas–liquid partitioning and retention further shape the accessible pressure response. These assumptions belong in the analysis and its stated limits.</p><h3>Separate acquisition from interpretation</h3><p>Recording the pressure and environmental channels supports later inspection of baseline behaviour, transient events, and processing choices. Filtered traces and fitted parameters remain linked to the measurement conditions that produced them.</p></section>
<section class="case-section" id="evidence"><p class="eyebrow">Measured evidence</p><h2>Long-duration data, documented conditions.</h2><p>The published pressure-quantification study reports continuous acquisition at <strong>1 Hz</strong>, with individual measurements extending <strong>beyond 70 hours at 37 °C</strong> and <strong>over 200 hours at room temperature</strong>. The tested geometry used 6 mL of solution and 4 mL of headspace in 10 mL tubes.</p><p>These results establish long-duration observability within the tested setup. The reported durations describe host-logged experiments; battery autonomy and industrial qualification were outside that evaluation.</p><p>On the optical side, the measurement platform was compared with a reference UV–vis instrument and an absorbance model. The <a class="inline-link" href="https://doi.org/10.1016/j.snb.2025.138667" target="_blank" rel="noopener noreferrer">published optical study</a> documents the calibration and validation conditions.</p><div class="technical-note"><strong>The transferable result</strong>A complete path from sensor integration to quantitative interpretation, with experimental conditions and measurement boundaries made explicit.</div></section>
<section class="case-section" id="on-device"><p class="eyebrow">Current technical direction</p><h2>Bring signal-quality assessment onto the device.</h2><p>A related ESP32-S2 research project combines adaptive pressure smoothing with temperature-based disturbance flagging. Four firmware variants compare raw acquisition, fixed Savitzky–Golay filtering, adaptive smoothing, and adaptive smoothing with exported Isolation Forest inference.</p><p>The current V3/V4 implementation uses a custom symmetric smoothing kernel and a SURE-inspired objective. It retains raw measurements and logs the filter state and temperature-derived flags. The repository includes recorded outputs, example data, plots, and whole-node power comparisons; development and a journal manuscript are ongoing.</p><p>This collaborative work builds on Ahmet Yasar Ayfer's student project. It is a separate development and evaluation effort from the journal results above. Temperature-derived flags indicate disturbances for inspection and require interpretation in the measurement context.</p><p><a class="button" href="https://github.com/abhisheksharma0217/esp32-sensing-pipeline" target="_blank" rel="noopener noreferrer">View research repository <span aria-hidden="true">↗</span></a></p></section>
<section class="case-section" id="sources"><p class="eyebrow">Supporting work</p><h2>Read the published methods.</h2><a class="reading-link" href="https://doi.org/10.1021/acsomega.6c06043" target="_blank" rel="noopener noreferrer">Pressure-derived gas accumulation and kinetic quantification ↗<span>Sharma et al. · ACS Omega · 2026 · DOI: 10.1021/acsomega.6c06043</span></a><a class="reading-link" href="https://doi.org/10.1016/j.snb.2025.138667" target="_blank" rel="noopener noreferrer">Optical absorbance sensing and experimental validation ↗<span>Sharma et al. · Sensors and Actuators B: Chemical · 2026 · DOI: 10.1016/j.snb.2025.138667</span></a><a class="reading-link" href="https://doi.org/10.1021/acsomega.5c07255" target="_blank" rel="noopener noreferrer">Pressure sensing and kinetic modelling ↗<span>Sharma et al. · ACS Omega · 2025 · DOI: 10.1021/acsomega.5c07255</span></a></section>
<a class="next-project" href="./etesting.html"><div><p class="eyebrow">Next case study</p><h3>e-Testing: operational software.</h3></div><span class="arrow" aria-hidden="true">↗</span></a></div></div></div></main>'''
page('sensing.html','Embedded Sensing & Measurement | Abhishek Sharma','An engineering case study in optical and pressure sensing, ESP32 acquisition, long-duration measurements and model-based interpretation.',sensing)

etesting=case_top('02 / Operational software','Keeping clinical reporting<br>maintainable.','e-Testing: a hospital intranet platform for finding psychological test results, generating reports, and maintaining instrument-specific workflows.',[('Context','University Medical Center Freiburg'),('My contribution','Development, maintenance, reporting automation, and technical handover'),('Stack','Flask · MariaDB · Apache · Linux'),('Focus','Repeatable integration and operational continuity')])
etesting+='''<div class="case-layout"><nav class="case-nav" aria-label="Case study sections"><a href="#problem">The problem</a><a href="#system">The system</a><a href="#contribution">My contribution</a><a href="#decisions">Engineering decisions</a><a href="#handover">Technical handover</a></nav><div class="case-content">
<section class="case-section" id="problem"><p class="eyebrow">The problem</p><h2>Every instrument adds a maintenance path.</h2><p>A psychological test can have its own data structure, report layout, age range, and export requirements. Supporting a new instrument requires coordinated changes across database records, application code, templates, and reporting configuration.</p><p>My work on e-Testing connected these pieces into a maintainable workflow for a hospital intranet application. The responsibility extended through ongoing changes, deployment, and the documentation needed for a successor to continue the work.</p></section>
<section class="case-section" id="system"><p class="eyebrow">The system</p><h2>From stored results to accessible reports.</h2><p>The Flask application connects a MariaDB database with search, instrument-specific result pages, report links, and automated CSV processing. It runs on a Linux server through Apache and mod_wsgi, with LDAP-backed sign-in.</p><div class="workflow" role="group" aria-label="Reporting workflow"><div class="workflow-step"><span>01</span><h3>Instrument data</h3><p>Database records and instrument definitions.</p></div><div class="workflow-step"><span>02</span><h3>Application logic</h3><p>Models, routes, templates, and configured processing.</p></div><div class="workflow-step"><span>03</span><h3>Results &amp; reports</h3><p>Searchable entries, report views, and CSV exports.</p></div></div><p>This overview describes the software architecture. Clinical records, internal addresses, and authentication details are excluded from the case study.</p></section>
<section class="case-section" id="contribution"><p class="eyebrow">My contribution</p><h2>Maintain the application and the change process.</h2><ul><li><strong>Application development:</strong> maintained result lookup, instrument-specific routes, report templates, and the data connections supporting them.</li><li><strong>Reporting automation:</strong> generalized the CSV-processing workflow around per-instrument configuration and YAML mappings.</li><li><strong>Instrument integration:</strong> documented the coordinated changes needed across the database, application, report links, and exports.</li><li><strong>Operational handover:</strong> prepared practical documentation for source control, development-to-production changes, and file and directory permissions.</li></ul></section>
<section class="case-section" id="decisions"><p class="eyebrow">Engineering decisions</p><h2>Make recurring changes explicit.</h2><h3>Move instrument variation into configuration</h3><p>The generalized CSV pipeline uses instrument-specific configuration and YAML mappings. This gives maintainers a defined place to describe export behaviour and removes reliance on hard-coded instrument prefixes in the shared workflow.</p><h3>Follow the entire lookup path</h3><p>A valid report route is one dependency in a longer chain. During an instrument addition, a missing entry in the application's main instrument lookup prevented the report from being found. Tracing that dependency shaped the handover instructions for future additions.</p><h3>Treat permissions as part of deployment</h3><p>Moving a working change onto the production server can introduce ownership and access differences. The handover covers permissions for both individual files and complete directories, alongside the source-control workflow.</p></section>
<section class="case-section" id="handover"><p class="eyebrow">Technical handover</p><h2>Leave a system someone else can maintain.</h2><p>The handover is organised around the tasks a successor needs to perform: obtain the project, work with the main branch, move changes into production, and add or update an instrument.</p><table class="facts-table"><caption class="eyebrow" style="text-align:left;margin-bottom:8px">Instrument changes: the connected parts</caption><thead><tr><th scope="col">Part</th><th scope="col">What the maintainer checks</th></tr></thead><tbody><tr><th scope="row">Data layer</th><td>Database table, model mapping, and instrument registry.</td></tr><tr><th scope="row">Report access</th><td>Application route, report template, and report-link mapping.</td></tr><tr><th scope="row">Exports</th><td>CSV configuration, YAML mapping, and output location.</td></tr><tr><th scope="row">Deployment</th><td>Source revision, production transfer, and file and directory access.</td></tr></tbody></table><div class="technical-note"><strong>What this work demonstrates</strong>Responsibility across application code, data workflows, deployment, and technical knowledge transfer. The maintenance process is part of the engineering deliverable.</div></section>
<a class="next-project" href="./sensing.html"><div><p class="eyebrow">Related case study</p><h3>Embedded sensing &amp; measurement.</h3></div><span class="arrow" aria-hidden="true">↗</span></a></div></div></div></main>'''
page('etesting.html','e-Testing: Operational Software | Abhishek Sharma','A case study in clinical reporting software, instrument integration, configuration-driven CSV processing, deployment and technical handover.',etesting)
print('Authored index.html, sensing.html, and etesting.html')
